name: Generate and Upload Zip Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download ads.txt
      run: curl -o ads.txt https://blocklist.oli11gh.top/f/ads.txt

    - name: Create zip file
      run: zip $(date +"%d.%m.%y").zip ads.txt

    - name: Generate filename
      id: filename
      run: echo "::set-output name=filename::$(date +"%d.%m.%y").zip"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ steps.filename.outputs.filename }}
        token: ${{ secrets.TOKEN }}
        tag_name: v0.1
