name: Backup Blocklist

on: push

jobs:
  backup_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Files
      run: |
        mkdir -p backup
        curl -o backup/ads.txt https://blocklist.oli11gh.top/f/ads.txt
        curl -o backup/ads-2.txt https://blocklist.oli11gh.top/f/ads-2.txt
        curl -o backup/ads-3.txt https://blocklist.oli11gh.top/f/ad-s3.txt
        curl -o backup/gen.txt https://blocklist.oli11gh.top/f/gen.txt

    - name: Create ZIP Archive
      run: |
        cd backup
        zip -r "$(date +"%y.%m.%d").zip" ./*.txt

    - name: Upload ZIP to Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.repository.releases_url }}
        asset_path: ./backup/$(date +"%y.%m.%d").zip
        asset_name: $(date +"%y.%m.%d").zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
